model:
  pretrained_weights: "google/vit-base-patch16-224-in21k"
  attack_method: PGD

training:
  num_epochs: 1
  learning_rate: 2e-5
  batch_size: 10
  save_log: False

dataset:
  name: "cifar10"
  logs: "logs/"